name: Build and deploy .NET app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore Sample_source_code_ASP_dot_net_core_web/Sample_source_code_ASP_dot_net_core_web.csproj

    - name: Build
      run: dotnet build Sample_source_code_ASP_dot_net_core_web/Sample_source_code_ASP_dot_net_core_web.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Sample_source_code_ASP_dot_net_core_web/Sample_source_code_ASP_dot_net_core_web.csproj -c Release -o publish

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ashwaniportal1
        package: publish
